version: '3.8'

services:
  notes-server:
    build: .
    container_name: notes-server-go
    restart: unless-stopped
    environment:
      - PORT=8080
      - HOST=0.0.0.0
    volumes:
      # Volumes для постоянного хранения данных
      - notes_data:/app/data
      - notes_uploads:/app/uploads
      - notes_backups:/app/user_backups
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/Service/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # DockHost автоматически назначит порт
    # ports:
    #   - "8080:8080"

volumes:
  notes_data:
    driver: local
  notes_uploads:
    driver: local
  notes_backups:
    driver: local 