name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 2.8.122

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  oktoast: ^3.4.0
  intl: 0.19.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  mask_text_input_formatter: ^2.4.0
  markdown: ^7.1.2
  flutter_markdown: ^0.6.18
  image_picker: ^1.0.7
  win32: ^5.3.0
  ffi: ^2.1.0
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  workmanager: ^0.5.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  share_plus: ^7.2.1
  file_picker: ^8.0.0
  msix: ^3.16.9
  cached_network_image: ^3.3.1
  crypto: ^3.0.3
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
