name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  oktoast: ^3.3.2
  intl: ^0.17.0
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.0.11
  mask_text_input_formatter: ^2.4.0
  markdown: ^7.1.2
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
