name: Build macOS Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      # Установим Flutter (если требуется, можно использовать кэширование)
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # укажите нужную версию

      - name: Flutter Doctor
        run: flutter doctor

      # Включение поддержки macOS Desktop
      - name: Enable macOS Desktop
        run: flutter config --enable-macos-desktop

      # Получаем зависимости
      - name: Get Flutter packages
        run: flutter pub get

      # Собираем релизную сборку для macOS
      - name: Build macOS Release
        run: flutter build macos --release

      # Сохраним артефакт сборки
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-app
          path: build/macos/Build/Products/Release/*.app
