name: Build macOS Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'  # укажите нужную версию

      - name: Flutter Doctor
        run: flutter doctor

      - name: Enable macOS Desktop
        run: flutter config --enable-macos-desktop

      - name: Get Flutter packages
        run: flutter pub get

      - name: Build macOS Release
        run: flutter build macos --release

      - name: Create DMG
        run: |
          # Замените "MyApp" на фактическое имя вашего приложения (без расширения .app)
          APP_NAME="flutter_application_1"
          APP_PATH="build/macos/Build/Products/Release/${APP_NAME}.app"
          DMG_NAME="${APP_NAME}.dmg"
          hdiutil create -volname "$APP_NAME" -srcfolder "$APP_PATH" -ov -format UDZO "$DMG_NAME"

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: flutter_application_1.dmg
