name: Commit-Based Release

on:
  push:
    branches: [ main ]

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Get current version
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | tr -d ' ')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"

      - name: Check if version was changed in this commit
        id: version_changed
        run: |
          # Получаем предыдущий коммит
          PREV_COMMIT=$(git rev-parse HEAD~1)
          
          # Проверяем, изменилась ли версия в pubspec.yaml
          CURRENT_VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | tr -d ' ')
          PREV_VERSION=$(git show $PREV_COMMIT:pubspec.yaml | grep '^version:' | sed 's/version: //' | tr -d ' ')
          
          if [ "$CURRENT_VERSION" != "$PREV_VERSION" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Version changed from $PREV_VERSION to $CURRENT_VERSION"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "Version not changed ($CURRENT_VERSION)"
          fi

      - name: Check if tag exists
        id: check_tag
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          TAG="v${{ steps.version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag $TAG already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Tag $TAG does not exist"
          fi

      - name: Create and push tag
        if: steps.version_changed.outputs.changed == 'true' && steps.check_tag.outputs.exists == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          TAG="v${{ steps.version.outputs.version }}"
          git tag $TAG
          git push origin $TAG
          echo "Created and pushed tag: $TAG"
          echo "This will trigger the release workflow automatically"

      - name: Skip release
        if: steps.version_changed.outputs.changed == 'false'
        run: |
          echo "Version not changed, skipping release creation" 