name: Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Verify pubspec.yaml
        run: |
          # Проверяем, что версия указана корректно
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Неверный формат версии: $VERSION"
            echo "Версия должна быть в формате X.Y.Z"
            exit 1
          fi
          echo "✅ Версия корректна: $VERSION" 